name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DEFAULT_PYTHON: "3.10"

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: psf/black@23.9.1

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run Pylint
        run: |
          pylint office365

  pytest:
    runs-on: ubuntu-latest
    needs:
      - ruff
      - black
      - pylint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Test with pytest
        env:
          office365_python_sdk_securevars: ${{ secrets.OFFICE365_PYTHON_SDK_SECUREVARS }}
        run: |
          echo "${{env.office365_python_sdk_securevars}}"
          pytest

# - name: Lint with flake8
#   run: |
#     # stop the build if there are Python syntax errors or undefined names
#     flake8 office365 --count --select=E9,F63,F7,F82 --show-source --statistics
#     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#     flake8 office365 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
